server:
  port: 8888

spring:
  application:
    name: lumina-gateway
  cloud:
    gateway:
      routes:
        - id: ai-service-route
          uri: http://localhost:8081
          predicates:
            - Path=/ai/**
